training:
  max_steps: 100000
  pix2pix_disc_weight: 0.5
    
eval:
  output_path: "outputs/"
  log_freq: 10
  val_freq: 2000

data:
  train_data_path: "/bigdata/casus/MLID/maria/VIRVS_data/IAV/processed/train"
  val_data_path:  "/bigdata/casus/MLID/maria/VIRVS_data/IAV/processed/val"
  batch_size: 8
  im_size: 256
  ch_in: [0]  

neptune:
  name: "Virtual_Stain"
  project: "mlid/test"